textutils.slowPrint("WELCOME TO CATAIOS!")
print("*---*")
sleep(0.1)
term.blit("|CAT|","22342","fffff")
sleep(0.1)
term.blit("| I |","22342","fffff")
sleep(0.1)
term.blit("| OS|","22342","fffff")
sleep(0.1)
print("*---*")
print("")
print("CATAIOS is a special purpose CC:T os for use with redstone and create")
sleep(0.5)
print("The system comes with the options to install a wide range of tools")
sleep(0.5)
print("")
print("CREDDITS:")
sleep(0.5)
print("AIO")
sleep(0.5)
term.setBackgroundColor(colors.blue)
print("               \n               \n               \n               \n               ")
sleep(0.25)
term.blit("               ","eeeeeeeeeeeeeee","eeeeeeeeeeeeeee")
term.blit("               ","eeeee44444eeeee","eeeee44444eeeee")
term.blit("               ","eeeeee4e4eeeeee","eeeeee4e4eeeeee")
term.blit("               ","eeeeee4e4eeeeee","eeeeee4e4eeeeee")
term.blit("               ","eeeeeeeeeeeeeee","eeeeeeeeeeeeeee")
sleep(0.25)
term.setBackgroundColor(colors.black)
print("               \n               \n               \n               \n               ")
sleep(0.25)
term.setBackgroundColor(colors.pink)
print("               \n               \n               \n               \n               ")
sleep(0.25)
term.setBackgroundColor(colors.yellow)
print("               \n               \n               \n               \n               ")
sleep(0.25)
term.setBackgroundColor(colors.cyan)
print("               \n               \n               \n               \n               ")
sleep(0.25)
print("Cat17katze")
sleep(0.5)
term.setBackgroundColor(colors.pink)
print("               \n               \n               \n               \n               ")
sleep(0.25)
term.setBackgroundColor(colors.yellow)
print("               \n               \n               \n               \n               ")
sleep(0.25)
term.setBackgroundColor(colors.cyan)
print("               \n               \n               \n               \n               ")
sleep(0.25)
