term.clear()
term.setCursorPos(1,1)
textutils.slowPrint("WELCOME TO CATAIOS!")
print("*---*")
sleep(0.1)
term.blit("|CAT|","22342","fffff")
sleep(0.1)
term.blit("| I |","22342","fffff")
sleep(0.1)
term.blit("| OS|","22342","fffff")
sleep(0.1)
print("*---*")
print(">>Please wait while we finish configuring your computer!<<")
shell.run("creddits")
